
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: vectrieve-qdrant
    ports:
      - "6333:6333"  # Відкриваємо порт назовні, щоб локальний Python його бачив
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always

  db:
    image: postgres:15-alpine
    container_name: vectrieve-postgres
    environment:
      POSTGRES_USER: vectrieve
      POSTGRES_PASSWORD: vectrieve_password
      POSTGRES_DB: vectrievedb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always