"""add_admin_rbac_telemetry

Revision ID: 31dcc69db8de
Revises: e076dee3d986
Create Date: 2026-07-15 01:33:43.689813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31dcc69db8de'
down_revision: Union[str, Sequence[str], None] = 'e076dee3d986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetrylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dense_latency', sa.Float(), nullable=False),
    sa.Column('sparse_latency', sa.Float(), nullable=False),
    sa.Column('rerank_latency', sa.Float(), nullable=False),
    sa.Column('llm_latency', sa.Float(), nullable=False),
    sa.Column('total_latency', sa.Float(), nullable=False),
    sa.Column('tokens_generated', sa.Integer(), nullable=False),
    sa.Column('tokens_per_second', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetrylog_query_id'), 'telemetrylog', ['query_id'], unique=False)
    op.create_index(op.f('ix_telemetrylog_user_id'), 'telemetrylog', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_index(op.f('ix_telemetrylog_user_id'), table_name='telemetrylog')
    op.drop_index(op.f('ix_telemetrylog_query_id'), table_name='telemetrylog')
    op.drop_table('telemetrylog')
    # ### end Alembic commands ###
