"""add_spaces

Revision ID: 76787ff9dbde
Revises: 0003
Create Date: 2026-07-12 19:47:59.030267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '76787ff9dbde'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filerecord_filename'), table_name='filerecord')
    op.drop_table('filerecord')
    op.alter_column('chathistory', 'sources',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('chathistory', 'attached_filenames',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('chatsession', sa.Column('space_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_chatsession_space_id'), 'chatsession', ['space_id'], unique=False)
    op.create_foreign_key(None, 'chatsession', 'space', ['space_id'], ['id'])
    op.add_column('document', sa.Column('space_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('document', 'summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_document_space_id'), 'document', ['space_id'], unique=False)
    op.create_foreign_key(None, 'document', 'space', ['space_id'], ['id'])
    op.alter_column('user_settings', 'local_model_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('user_settings', 'groq_api_key',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('user_settings', 'qdrant_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('user_settings', 'qdrant_api_key',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('user_settings', 'ollama_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_settings_user_id_fkey', 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_settings', 'ollama_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_settings', 'qdrant_api_key',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_settings', 'qdrant_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_settings', 'groq_api_key',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_settings', 'local_model_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('document_space_id_fkey', 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_space_id'), table_name='document')
    op.alter_column('document', 'summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('document', 'space_id')
    op.drop_constraint('chatsession_space_id_fkey', 'chatsession', type_='foreignkey')
    op.drop_index(op.f('ix_chatsession_space_id'), table_name='chatsession')
    op.drop_column('chatsession', 'space_id')
    op.alter_column('chathistory', 'attached_filenames',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chathistory', 'sources',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('filerecord',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chunks_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('filerecord_pkey'))
    )
    op.create_index(op.f('ix_filerecord_filename'), 'filerecord', ['filename'], unique=False)
    # ### end Alembic commands ###
