"""add_space_llm_configs

Revision ID: e076dee3d986
Revises: 76787ff9dbde
Create Date: 2026-07-14 14:26:38.186858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e076dee3d986'
down_revision: Union[str, Sequence[str], None] = '76787ff9dbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('space', sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('space', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('space', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.add_column('space', sa.Column('top_p', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'top_p')
    op.drop_column('space', 'max_tokens')
    op.drop_column('space', 'temperature')
    op.drop_column('space', 'llm_model')
    op.drop_column('space', 'llm_provider')
    # ### end Alembic commands ###
